import { useState, useEffect } from 'react';
import { Ticket, Check, UserRound, RotateCcw } from 'lucide-react';
import Input from '../../components/Input';
import Select from '../../components/Select';
import Button from '../../components/Button';
import PriorityBadge from '../../components/PriorityBadge';
import PatientQueue from '../../components/PatientQueue';
import { buscarAtendimento, emitirSenha } from '../../services/ticketService';
import { TIPOS } from '../../constants/senha';
const emptyForm = { name: '', identification: '', type: '', priority: 'SG' };
export default function EmissaoSenha() {
  const [form, setForm] = useState(emptyForm);
  const [ticket, setTicket] = useState(null);
  const [errors, setErrors] = useState({});
  const [fila, setFila] = useState([]);
  const [sending, setSending] = useState(false);
  const [submitError, setSubmitError] = useState('');
  useEffect(() => { buscarAtendimento().then(d => setFila(d.fila)).catch(() => setSubmitError('Não foi possível carregar a fila.')); }, []);
  const field = key => ({ value: form[key], onChange: e => { setForm({ ...form, [key]: e.target.value }); setErrors({ ...errors, [key]: '' }); } });
  const emit = async e => { e.preventDefault(); const nextErrors = { name: !form.name.trim() ? 'Informe o nome do paciente.' : '', identification: !form.identification.trim() ? 'Informe o CPF ou outra identificação.' : '', type: !form.type ? 'Selecione o tipo de atendimento.' : '' }; setErrors(nextErrors); if (Object.values(nextErrors).some(Boolean)) return; setSending(true); setSubmitError(''); try { const senha = await emitirSenha(form); setTicket(senha); setFila((await buscarAtendimento()).fila); } catch { setSubmitError('Não foi possível emitir a senha. Tente novamente.'); } finally { setSending(false); } };
  return <><div className="page-heading"><div><div className="eyebrow">RECEPÇÃO DO LABORATÓRIO</div><h1>Emissão de senha</h1><p>Preencha os dados do paciente para preparar uma senha de atendimento.</p></div></div><div className="emission-grid"><section className="panel form-panel"><div className="section-heading"><div><h2><UserRound size={18} />Dados do paciente</h2><p>Os campos com <span className="required">*</span> são obrigatórios.</p></div></div><form onSubmit={emit} noValidate><Input id="patient-name" label="Nome do paciente" placeholder="Digite o nome completo" autoComplete="off" required error={errors.name} {...field('name')} /><Input id="identification" label="CPF / Identificação" placeholder="Digite o CPF ou documento de identificação" required error={errors.identification} hint="Utilize apenas dados fictícios nesta demonstração." {...field('identification')} /><div className="form-row"><Select id="service-type" label="Tipo de atendimento" required error={errors.type} options={[{ value: '', label: 'Selecionar atendimento' }, ...['Coleta de exames', 'Exame laboratorial', 'Retirada de resultados'].map(value => ({ value, label: value }))]} {...field('type')} /><Select id="priority" label="Tipo de senha" required options={Object.keys(TIPOS).map(value => ({ value, label: `${value} · ${TIPOS[value]}` }))} {...field('priority')} /></div>{submitError && <div className="field-error" role="alert">{submitError}</div>}<div className="form-actions"><Button type="button" variant="secondary" onClick={() => { setForm(emptyForm); setErrors({}); setTicket(null); }}><RotateCcw size={15} />Limpar</Button><Button type="submit" loading={sending}><Ticket size={17} />Emitir senha</Button></div></form></section><section className={`panel generated-panel ${ticket ? 'has-ticket' : ''}`} aria-live="polite"><div className="section-heading"><div><h2><Ticket size={18} />Senha gerada</h2><p>{ticket ? 'Prévia da senha de atendimento.' : 'A senha aparecerá aqui após a emissão.'}</p></div></div>{ticket ? <div className="ticket-preview"><span className="ticket-label">SENHA DE ATENDIMENTO</span><strong className="generated-number">{ticket.ticket}</strong><span className="ticket-unit">Laboratório · Unidade Nassau</span><dl><div><dt>Paciente</dt><dd>{ticket.name}</dd></div><div><dt>Tipo de atendimento</dt><dd>{ticket.type}</dd></div><div><dt>Tipo de senha</dt><dd><PriorityBadge value={ticket.priority} /></dd></div></dl><div className="ticket-success"><Check size={16} />Senha de demonstração emitida</div></div> : <div className="ticket-placeholder"><span className="placeholder-icon"><Ticket size={30} /></span><strong>Pronto para um novo atendimento</strong><p>Preencha os dados ao lado.<br />A prévia da senha será exibida neste espaço.</p></div>}</section></div><PatientQueue patients={fila} /></>;
}
